import { 
  Fuel, ShoppingBasket, Hash, CreditCard, BarChart3, 
  Settings, LogOut, Trash2, Printer, CheckCircle,
  XCircle, ChevronRight, RefreshCcw, UserCircle2, Clock, 
  Calculator, Scan, ShieldCheck, Ticket, Search, 
  History, ChevronLeft, ArrowLeft, Filter, FileText,
  User, Lock, Globe, Plus, Minus, Tag, Percent, Truck, 
  Keyboard, Delete as BackspaceIcon, Banknote, QrCode, Gift, Terminal,
  WifiOff, PowerOff, RefreshCw, Droplets, Hand, ArrowUp, PauseCircle, AlertTriangle, Bell, Zap
} from 'lucide-react';

export const Icon = {
  Fuel,
  Cart: ShoppingBasket,
  Keypad: Hash,
  Payment: CreditCard,
  Analytics: BarChart3,
  Settings,
  Logout: LogOut,
  Delete: Trash2,
  Print: Printer,
  Success: CheckCircle,
  Close: XCircle,
  ChevronRight,
  ChevronLeft,
  ArrowBack: ArrowLeft,
  Reset: RefreshCcw,
  User: UserCircle2,
  Time: Clock,
  Cash: Banknote,
  Scan: QrCode,
  Security: ShieldCheck,
  Voucher: Ticket,
  Ticket,
  Search,
  History,
  Filter,
  Document: FileText,
  AuthUser: User,
  AuthLock: Lock,
  Globe,
  Plus,
  Minus,
  Tag,
  Percent,
  Truck,
  Keyboard,
  Backspace: BackspaceIcon,
  Gift,
  Terminal,
  Disconnected: WifiOff,
  Closed: PowerOff,
  Connecting: RefreshCw,
  Droplets,
  Hand,
  ArrowUp,
  Suspend: PauseCircle,
  Alert: AlertTriangle,
  Bell,
  Zap
};